-- Aseprite 1.3.18.5. Native alpha extraction from the retained generated RGB.
-- aseprite -b --script-param root=/absolute/repository --script this-file.lua
-- No resampling or RGB replacement touches the character in the master/export.
local root=assert(app.params.root,'root is required'):gsub('/$','')
local folder=root..'/assets/npcs/keeper/'
local previews=folder..'previews/dialogue/'
app.fs.makeAllDirectories(previews)
local source=folder..'dialogue-portrait-generated.png'
local original=Image{fromFile=source}
assert(original and original.width==1024 and original.height==1536,'Unexpected reviewed source dimensions')
local width,height=original.width,original.height
local pc=app.pixelColor
local candidate,visited,remove={},{},{}
local components={}
local function luminance(pixel)
  return (pc.rgbaR(pixel)+pc.rgbaG(pixel)+pc.rgbaB(pixel))/3
end
for it in original:pixels() do
  local pixel=it()
  local r,g,b=pc.rgbaR(pixel),pc.rgbaG(pixel),pc.rgbaB(pixel)
  local low,high=math.min(r,g,b),math.max(r,g,b)
  if low>=170 and high-low<=10 then candidate[it.y*width+it.x+1]=true end
end
-- Four-connected components preserve isolated ivory highlights. Enclosed
-- background has both the light and gray checker tones; bright hair does not.
for first in pairs(candidate) do
  if not visited[first] then
    local queue,head={first},1
    visited[first]=true
    local x0,y0,x1,y1=width,height,0,0
    local low,high=255,0
    local edge=false
    while head<=#queue do
      local index=queue[head];head=head+1
      local x,y=(index-1)%width,math.floor((index-1)/width)
      x0=math.min(x0,x);x1=math.max(x1,x);y0=math.min(y0,y);y1=math.max(y1,y)
      local value=luminance(original:getPixel(x,y));low=math.min(low,value);high=math.max(high,value)
      edge=edge or x==0 or y==0 or x==width-1 or y==height-1
      local function add(next)
        if candidate[next] and not visited[next] then visited[next]=true;queue[#queue+1]=next end
      end
      if x>0 then add(index-1) end
      if x<width-1 then add(index+1) end
      if y>0 then add(index-width) end
      if y<height-1 then add(index+width) end
    end
    local checker=#queue>=24 and low<225 and high>245
    local background=edge or checker
    if background then for _,index in ipairs(queue) do remove[index]=true end end
    if #queue>=8 then components[#components+1]={pixels=#queue,bounds={x0,y0,x1,y1},low=low,high=high,removed=background} end
  end
end
local cutout=Image(original)
local removed=0
for it in cutout:pixels() do
  if remove[it.y*width+it.x+1] then
    -- Keep every source RGB triplet, even underneath zero alpha.
    local p=it();it(pc.rgba(pc.rgbaR(p),pc.rgbaG(p),pc.rgbaB(p),0));removed=removed+1
  end
end
local sprite=Sprite(width,height,ColorMode.RGB)
sprite.layers[1].name='Keeper — original colors, background removed'
sprite:newCel(sprite.layers[1],1,cutout,Point(0,0))
local reference=sprite:newLayer();reference.name='Generated RGB — unmodified reference';reference.isVisible=false
sprite:newCel(reference,1,original,Point(0,0))
sprite.data=json.encode({source='dialogue-portrait-generated.png',method='native Aseprite connected neutral checker removal',rgb_preserved=true})
sprite:saveAs(folder..'dialogue-portrait.aseprite')
cutout:saveAs(folder..'dialogue-portrait.png')
-- Review-only composites are generated by Aseprite, never an image library.
local backgrounds={{24,18,32},{237,229,216},{122,25,102}}
for i,color in ipairs(backgrounds) do
  local full=Image(width,height,ColorMode.RGB);full:clear(pc.rgba(color[1],color[2],color[3],255))
  full:drawImage(cutout)
  full:saveAs(previews..'dialogue-portrait-review-'..i..'.png')
  local small=Image(full);small:resize{width=320,height=480,method='bilinear'}
  small:saveAs(previews..'dialogue-portrait-review-small-'..i..'.png')
end
local details=Image(cutout,Rectangle(320,0,448,416))
local detail_background=Image(details.width,details.height,ColorMode.RGB)
detail_background:clear(pc.rgba(24,18,32,255));detail_background:drawImage(details)
detail_background:saveAs(previews..'dialogue-portrait-review-hair.png')
local report=io.open(previews..'dialogue-portrait-alpha-review.json','w')
report:write(json.encode({width=width,height=height,removed=removed,components=components}));report:close()
sprite:close()
print('Keeper alpha: '..removed..' fully transparent source pixels; RGB unchanged.')
